services:
  - type: web
    name: audiora-backend
    env: docker
    plan: free
    rootDir: backend
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILE
        value: prod
      - key: BACKEND_BASE_URL
        sync: false
      - key: FRONTEND_BASE_URL
        sync: false
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: YOUTUBE_CLIENT_ID
        sync: false
      - key: YOUTUBE_CLIENT_SECRET
        sync: false
      - key: EMAIL_USERNAME
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: audiora-db
          property: connectionString
      - key: DATABASE_USERNAME
        fromDatabase:
          name: audiora-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: audiora-db
          property: password

databases:
  - name: audiora-db
    plan: free
    databaseName: audiora
    user: audiora
